### ISSUE TITLE
Plugin is not working :( 

### ISSUE THREAD

**Issue by ondrarethy** [bleutzinn/grav-plugin-editable-contenttools#10]
Hi!

I have a very little problem. It's not working for me :D I don't know if I'm doing anything wrong, but I think everything should be alright. I install it through bin/gpm on clear installation of GRAV and nothing happen. I can see it in plugins, its enabled, I gave admin permission in that file, but that's all.

Can you please share me a skeleton? 

Thanks a lot!
Andrew

**Comment by bleutzinn** [comment]
A few things to check before resorting to a skeleton. 

Can the frontend user log in on the frontend? You should see the username and a log out link in the menu.

If these are missing you can do two things:
1. Provide a Log in page (see the Login plugin documentation)
2. If you use the Admin plugin you can disable Split Session in config, log out and log in again in Admin. After that the Admin user is automatically logged in on the frontend

This should do the trick.

**Comment by ondrarethy** [comment]
Yes! It was a session split... 😄  I was too excited that I found perfect plugin, which I was searching for months, that I forgot to RTFM...

Thanks a lot for this plugin! I hope that there will be support for it for a very long time 😄 

Have a nice day!

**Comment by bleutzinn** [comment]
Glad to have been of help.

**Comment by ondrarethy** [comment]
So, its working now. But only for normal pages. If i wanna try modular one, it will just display [editable] like the text. Everything is same, page is same, but "parent" is modular template. 

Are modular pages supported?

**Comment by bleutzinn** [comment]
No it does not. See the notice starting with “Important” in the ReadMe file. Sorry.
