### ISSUE TITLE
Create a waiting for admin approval after user's editing

### ISSUE THREAD

**Issue by maskho** [bleutzinn/grav-plugin-editable-contenttools#11]
Hi, is there a feature in this plugin to handle the waiting for admin approval mechanism?
The mechanism is as follows:
- Users edit content on the front end
- A notification appears that the editing results are waiting for admin approval first
- After that, the admin will check the content changes
- If approved, the content on the page will change
If there is no such feature, can this request be included in the next development plan?

Thanks!

**Comment by bleutzinn** [comment]
There is no such feature at this moment. Such content workflow would be a great feature in Grav. If added I think it should be a separate plugin.
