### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by k-512** [bleutzinn/grav-plugin-editable-contenttools#12]
After installing the plugin with Grav Admin and adding [editable] ... [/editable] to the content, the page will not load and show this error:

> SplFileInfo::isFile(): open_basedir restriction in effect. File(/var/www/clients/client1/web1/webeditable-contenttools-api/editor.js) is not within the allowed path(s)

The base dir is: /var/www/clients/client1/web1/web/

Any idea what's going wrong? Looks like the URL is not formed correctly.

Thanks

**Comment by bleutzinn** [comment]
Can you please test changing the line:
https://github.com/bleutzinn/grav-plugin-editable-contenttools/blob/f375215e4384e06fec573484f3d3e4061a7c5bf3/editable-contenttools.php#L44 
into:
```
$assets->addJs(Uri::cleanPath('/' . $this->plugin_name . '-api' . $route . '/' . 'editor.js'));
```

Please let me know whether or not this works for you or in case you have questions.

**Comment by k-512** [comment]
The line was changed and now the plugin works perfectly.

Thank you very much!

**Comment by bleutzinn** [comment]
Great. I've just made a new release so everyone can benefit. Thanks for reporting and testing.
