### ISSUE TITLE
no edit button after installation

### ISSUE THREAD

**Issue by markusritschel** [bleutzinn/grav-plugin-editable-contenttools#4]
Hi,

I recently stumbled upon your Grav plugin for frontend editing. So, today I installed it but unfortunately, the plugin is not working at all. I followed your instructions but there is no pencil button on the frontend appearing. Any suggestions on what the reason for that could be?
Thanks a lot in Advance!

Markus

**Comment by bleutzinn** [comment]
The plugin adds a Javascript file to the Twig bottom block of the current theme. However, not all themes define a bottom block.

I discovered the same problem when working on issue [#3](https://github.com/bleutzinn/grav-plugin-editable-contenttools/issues/3). For testing I use the [MultiLanguage skeleton for Grav](https://github.com/getgrav/grav-skeleton-multilang-site) which works with the [cacti theme](https://github.com/getgrav/grav-theme-cacti). It appeared that theme lacks a bottom block and the Javascript file is not added to the page at all.

A fix is on the way. In the mean time you could add a bottom block to your theme. See [grav-theme-antimatter/templates/partials/base.html.twig](https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L85).

**Comment by markusritschel** [comment]
First of all, thanks for your quick reply!
I'm actually using the *Quark* theme on a fresh installation of Grav which uses a `bottom block`. The following is an excerpt of  its `partials/base.html.twig`:
```twig
{% block bottom %}
    {{ assets.js('bottom')|raw }}
{% endblock %}
```
What I didn't know about so far but what I saw in the issue #3, is the usage of those `[editable name="myeditregion"]...[/editable]` areas. Still, there is no icon appearing.
It seems like the plugin is not really registered, since none of the assets I can see in your `editable-sontenttools.php` can be found in the source code of the rendered site. The plugin itself is enabled (visible both in the Admin panel and in the `editable-contenttools.yaml`). I also don't think it's something related to my browser, since your [demo](https://festeto.net/demo-grav-plugin-editable-contenttools/typography) is perfectly working.
I'm pretty new to Grav, so maybe I'm missing some (for you) obvious part? :-)

**Comment by markusritschel** [comment]
My `user/accounts/admin.yaml`  looks like
```yaml
state: enabled
access:
  admin:
    super: 'true'
    login: 'true'
  site:
    login: 'true'
    editable: 'true'
```

**Comment by markusritschel** [comment]
Ok, don't ask me why or how, but it's working now :-D
Originally, I changed the `split` option in my `system/config/system.yaml`. Now I tried it again doing it in the `user/config/system.yaml`. Maybe that was the issue. Anyway: problem solved :-)
But the thing with the `bottom block` could be maybe worth being mentioned in the README ;-)

**Comment by bleutzinn** [comment]
Great it's working now.

Of course I also can't tell why but one thing may be the actual user login into the frontend. The most convenient and quickest way is to set `session.split: false` in `user/config/system.yaml`.
