### ISSUE TITLE
The plugin is super, but it breaks the image display.

### ISSUE THREAD

**Issue by Dudaevskiy** [bleutzinn/grav-plugin-editable-contenttools#7]
In the body of the page, the text is wrapped as it should:

```
[editable name = "PageWrapp"]
text ....
[/editable]

![Image] (poster.jpg)
![] [3]
![][4]

[editable name="PageWrapp"]
text ....
[/editable]

[3]: 001-insert-audio-music-file-into-slideshow-100785890-large.jpg
[4]: 002-choose-the-play-in-background-button-for-entire-presentation-100785891-large.JPG
```

Why is an image that is not inside the shortcode not displayed?

**Comment by bleutzinn** [comment]
Try removing the space in `![Image] (poster.jpg)`.

**Comment by Dudaevskiy** [comment]
![not work](https://i.ibb.co/mF1w0y7/2019-09-27-15-31-51.jpg)

Not work

**Comment by Dudaevskiy** [comment]
In general, it doesn’t matter. The plugin https://github.com/BugHunter2k/grav-plugin-fred/blob/master/README.md   has become an excellent replacement.
