### ISSUE TITLE
Integration with Gantry 5?

### ISSUE THREAD

**Issue by NickSchick** [bleutzinn/grav-plugin-editable-contenttools#8]
I was wondering if there would be a way to add functionality where you could add the shortcode to a gantry 5 particle (maybe Custom HTML) then create [editable name="whatever"] for easy client adjustments on the frontend. 

This would be great - I have tried many things now to add this but I haven't had any success.

**Comment by bleutzinn** [comment]
Can you elaborate on what you did, what works and what doesn't? I have no experience with Gantry and frankly don't have the time to start experimenting with it.

**Comment by NickSchick** [comment]
So via Gantry you can use particles (not associated with an .md "page" file) and create content in many different positions. I have tried: 

- Custom HMTL (shortcode enabled) -- not working
- Inject Grav Page Plugin -- not working
- Grav Content -- not working
- I have adjusted to add (markdown="1") to push shortcode/markdown -- not working
- TWIG inject via "pages.find(/blahblah).content" -- not working
- Hardcoded js from contenttools instructions (this I had very little hope for but at least I could get it to show the edit feature via the page) -- working sorta meaning you can edit the text but it doesn't actually save

Basically Gantry is stripping the "shortcode" and changing it into part of the html (e.g. `<p>[editable]</p>`

If this feature would be awesome if you could add this shortcode at the point in which clients could adjust their own content without contacting me :)

This plugin is really great! On more simple projects the clients can really change what they need in a simple way. Its when we use the Framework that it became a bit of an issue (which surprises me because grav/gantry are the same developers - would think that the shortcode would process through.

 I totally understand about the time but I think once this feature would work with Native Gantry -- wow -- this is a great solution!

**Comment by bleutzinn** [comment]
That's an impressive list. From a [Gantry/Grav Gitter archive](https://gitter.im/gantry/gantry5/archives/2017/01/04) (use in page search to get to "shortcode") I get the impression that it's impossible to include shortcodes in particles.
However [[Solved] Markdown particle for Gantry 5](https://discourse.getgrav.org/t/solved-markdown-particle-for-gantry-5/5066) describes a way to include Markdown in a particle.
(Right now I can hardly resist the urge to express how much I dislike Gantry.)

**Comment by NickSchick** [comment]
Awesome find with the Markdown particle, however, it still processes [editable] as text or `<p>[editable]</p>` Tried to implement `data-editable="" data-name="region-0"` allows you to edit the text and save with no error. Upon refresh, changes are reverted.

What is interesting is when you use the "Page Content" Position, contenttools works perfectly. But only on this position

I appreciate your feedback maybe some other ideas?

**Comment by bleutzinn** [comment]
Did you experiment with the raw filter as mentioned later on in the forum post?

**Comment by NickSchick** [comment]
Yep both with and without

**Comment by NickSchick** [comment]
In addition - Markdown is processing (e.g. ### title will result a correctly displayed `<h3>title</h3>` )

**Comment by bleutzinn** [comment]
Getting the editor working in the generated page is one thing, saving changes is another.

One kind of last resort in forcing something into a page when normal procedures don't work is to inject it in the generated HTML code just before the page is served by Grav. This can be done in a plugin through the [onOutputGenerated](https://learn.getgrav.org/16/plugins/event-hooks#onoutputgenerated) event.

Upon a save action from the editor, the Editable with ContentTools Plugin expects a normal Grav page. It loads that page in memory and replaces any changed regions with the edited content received from the editor. However a particle is just a chunk of content. This may well be the show stopper I'm afraid.

**Comment by bleutzinn** [comment]
Closing dus to inactivity.
