### ISSUE TITLE
Change "textarea" to another element?

### ISSUE THREAD

**Issue by lheinitz20** [bleutzinn/grav-plugin-editable-contenttools#9]
**Hi,**

is it possible to change the created element ?
In my case I would like to change the element from textarea to a "span".
In the "content-tools.min.js" - file I found that: `document.createElement("textarea")` 
--> change to `document.createElement("textarea")` ?

Best regards 
Lars

**Comment by bleutzinn** [comment]
I'm unsure what you are trying to achieve. The file `content-tools.min.js` is the main Javascript code of ContentTools. So I suggest you create an issue in the [ContentTools repository](https://github.com/GetmeUK/ContentTools).
